#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


              typedef struct array_dims array_dims;
              struct array_dims {
                ptrdiff_t stride;
                ptrdiff_t lower_bound;
                ptrdiff_t extent;
              };

              typedef struct datatype datatype;
              struct datatype {
                size_t len;
                int ver;
                signed char rank;
                signed char type;
                signed short attribute;
              };
            
              typedef struct array_1d array_1d;
              struct array_1d {
                void *base_addr;
                size_t offset;
                datatype dtype;
                ptrdiff_t span;
                struct array_dims dim[1];
              };
            
              typedef struct array_2d array_2d;
              struct array_2d {
                void *base_addr;
                size_t offset;
                datatype dtype;
                ptrdiff_t span;
                struct array_dims dim[2];
              };
            
              typedef struct array_3d array_3d;
              struct array_3d {
                void *base_addr;
                size_t offset;
                datatype dtype;
                ptrdiff_t span;
                struct array_dims dim[3];
              };
            
              typedef struct array_4d array_4d;
              struct array_4d {
                void *base_addr;
                size_t offset;
                datatype dtype;
                ptrdiff_t span;
                struct array_dims dim[4];
              };
            
              typedef struct array_5d array_5d;
              struct array_5d {
                void *base_addr;
                size_t offset;
                datatype dtype;
                ptrdiff_t span;
                struct array_dims dim[5];
              };
            
              typedef struct array_6d array_6d;
              struct array_6d {
                void *base_addr;
                size_t offset;
                datatype dtype;
                ptrdiff_t span;
                struct array_dims dim[6];
              };
            
              typedef struct array_7d array_7d;
              struct array_7d {
                void *base_addr;
                size_t offset;
                datatype dtype;
                ptrdiff_t span;
                struct array_dims dim[7];
              };
            extern void __neo_orb_global_MOD_init_field(int32_t *ans_s, int32_t *ans_tp, int32_t *amultharm, int32_t *aintegmode);
extern void __neo_orb_global_MOD_init_params(int32_t *Z_charge, int32_t *m_mass, double *E_kin, double *adtau, double *adtaumax, double *arelerr);
extern void __neo_orb_global_MOD_init_integrator(array_1d *z0);
extern void __neo_orb_global_MOD_timestep_z(array_1d *z, int32_t *ierr);
extern void __neo_orb_global_MOD_timestep_sympl_z(array_1d *z, int32_t *ierr);
extern double __new_vmec_stuff_mod_MOD_rmajor;
extern double __new_vmec_stuff_mod_MOD_h_theta;
extern double __new_vmec_stuff_mod_MOD_h_phi;
extern void __cut_detector_global_MOD_init(array_1d *z);
extern void __cut_detector_global_MOD_trace_to_cut(array_1d *z, array_1d *var_cut, int32_t *cut_type, int32_t *ierr);


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 58), // void()(array_1d *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 27), // array_1d *
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  3 */ _CFFI_OP(_CFFI_OP_FUNCTION, 58), // void()(array_1d *, array_1d *, int32_t *, int32_t *)
/*  4 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  5 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  6 */ _CFFI_OP(_CFFI_OP_POINTER, 51), // int32_t *
/*  7 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION, 58), // void()(array_1d *, int32_t *)
/* 10 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 11 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 12 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 13 */ _CFFI_OP(_CFFI_OP_FUNCTION, 58), // void()(int32_t *, int32_t *, double *, double *, double *, double *)
/* 14 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 15 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 16 */ _CFFI_OP(_CFFI_OP_POINTER, 50), // double *
/* 17 */ _CFFI_OP(_CFFI_OP_NOOP, 16),
/* 18 */ _CFFI_OP(_CFFI_OP_NOOP, 16),
/* 19 */ _CFFI_OP(_CFFI_OP_NOOP, 16),
/* 20 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 21 */ _CFFI_OP(_CFFI_OP_FUNCTION, 58), // void()(int32_t *, int32_t *, int32_t *, int32_t *)
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 23 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 25 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 27 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // array_1d
/* 28 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // array_2d
/* 29 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // array_3d
/* 30 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // array_4d
/* 31 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // array_5d
/* 32 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 5), // array_6d
/* 33 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 6), // array_7d
/* 34 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 7), // array_dims
/* 35 */ _CFFI_OP(_CFFI_OP_ARRAY, 34), // array_dims[1]
/* 36 */ (_cffi_opcode_t)(1),
/* 37 */ _CFFI_OP(_CFFI_OP_ARRAY, 34), // array_dims[2]
/* 38 */ (_cffi_opcode_t)(2),
/* 39 */ _CFFI_OP(_CFFI_OP_ARRAY, 34), // array_dims[3]
/* 40 */ (_cffi_opcode_t)(3),
/* 41 */ _CFFI_OP(_CFFI_OP_ARRAY, 34), // array_dims[4]
/* 42 */ (_cffi_opcode_t)(4),
/* 43 */ _CFFI_OP(_CFFI_OP_ARRAY, 34), // array_dims[5]
/* 44 */ (_cffi_opcode_t)(5),
/* 45 */ _CFFI_OP(_CFFI_OP_ARRAY, 34), // array_dims[6]
/* 46 */ (_cffi_opcode_t)(6),
/* 47 */ _CFFI_OP(_CFFI_OP_ARRAY, 34), // array_dims[7]
/* 48 */ (_cffi_opcode_t)(7),
/* 49 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 8), // datatype
/* 50 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 51 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 21), // int32_t
/* 52 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 53 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 27), // ptrdiff_t
/* 54 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 5), // short
/* 55 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 3), // signed char
/* 56 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28), // size_t
/* 57 */ _CFFI_OP(_CFFI_OP_POINTER, 58), // void *
/* 58 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static void _cffi_d___cut_detector_global_MOD_init(array_1d * x0)
{
  __cut_detector_global_MOD_init(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f___cut_detector_global_MOD_init(PyObject *self, PyObject *arg0)
{
  array_1d * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (array_1d *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { __cut_detector_global_MOD_init(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f___cut_detector_global_MOD_init _cffi_d___cut_detector_global_MOD_init
#endif

static void _cffi_d___cut_detector_global_MOD_trace_to_cut(array_1d * x0, array_1d * x1, int32_t * x2, int32_t * x3)
{
  __cut_detector_global_MOD_trace_to_cut(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f___cut_detector_global_MOD_trace_to_cut(PyObject *self, PyObject *args)
{
  array_1d * x0;
  array_1d * x1;
  int32_t * x2;
  int32_t * x3;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "__cut_detector_global_MOD_trace_to_cut", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (array_1d *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (array_1d *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { __cut_detector_global_MOD_trace_to_cut(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f___cut_detector_global_MOD_trace_to_cut _cffi_d___cut_detector_global_MOD_trace_to_cut
#endif

static void _cffi_d___neo_orb_global_MOD_init_field(int32_t * x0, int32_t * x1, int32_t * x2, int32_t * x3)
{
  __neo_orb_global_MOD_init_field(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f___neo_orb_global_MOD_init_field(PyObject *self, PyObject *args)
{
  int32_t * x0;
  int32_t * x1;
  int32_t * x2;
  int32_t * x3;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "__neo_orb_global_MOD_init_field", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { __neo_orb_global_MOD_init_field(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f___neo_orb_global_MOD_init_field _cffi_d___neo_orb_global_MOD_init_field
#endif

static void _cffi_d___neo_orb_global_MOD_init_integrator(array_1d * x0)
{
  __neo_orb_global_MOD_init_integrator(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f___neo_orb_global_MOD_init_integrator(PyObject *self, PyObject *arg0)
{
  array_1d * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (array_1d *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { __neo_orb_global_MOD_init_integrator(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f___neo_orb_global_MOD_init_integrator _cffi_d___neo_orb_global_MOD_init_integrator
#endif

static void _cffi_d___neo_orb_global_MOD_init_params(int32_t * x0, int32_t * x1, double * x2, double * x3, double * x4, double * x5)
{
  __neo_orb_global_MOD_init_params(x0, x1, x2, x3, x4, x5);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f___neo_orb_global_MOD_init_params(PyObject *self, PyObject *args)
{
  int32_t * x0;
  int32_t * x1;
  double * x2;
  double * x3;
  double * x4;
  double * x5;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;

  if (!PyArg_UnpackTuple(args, "__neo_orb_global_MOD_init_params", 6, 6, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(16), arg2, (char **)&x2);
  if (datasize != 0) {
    x2 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(16), arg2, (char **)&x2,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(16), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(16), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(16), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(16), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(16), arg5, (char **)&x5);
  if (datasize != 0) {
    x5 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(16), arg5, (char **)&x5,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { __neo_orb_global_MOD_init_params(x0, x1, x2, x3, x4, x5); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f___neo_orb_global_MOD_init_params _cffi_d___neo_orb_global_MOD_init_params
#endif

static void _cffi_d___neo_orb_global_MOD_timestep_sympl_z(array_1d * x0, int32_t * x1)
{
  __neo_orb_global_MOD_timestep_sympl_z(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f___neo_orb_global_MOD_timestep_sympl_z(PyObject *self, PyObject *args)
{
  array_1d * x0;
  int32_t * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "__neo_orb_global_MOD_timestep_sympl_z", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (array_1d *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { __neo_orb_global_MOD_timestep_sympl_z(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f___neo_orb_global_MOD_timestep_sympl_z _cffi_d___neo_orb_global_MOD_timestep_sympl_z
#endif

static void _cffi_d___neo_orb_global_MOD_timestep_z(array_1d * x0, int32_t * x1)
{
  __neo_orb_global_MOD_timestep_z(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f___neo_orb_global_MOD_timestep_z(PyObject *self, PyObject *args)
{
  array_1d * x0;
  int32_t * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "__neo_orb_global_MOD_timestep_z", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (array_1d *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(6), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (int32_t *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(6), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { __neo_orb_global_MOD_timestep_z(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f___neo_orb_global_MOD_timestep_z _cffi_d___neo_orb_global_MOD_timestep_z
#endif

_CFFI_UNUSED_FN
static void _cffi_checkfld__array_1d(array_1d *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { void * *tmp = &p->base_addr; (void)tmp; }
  (void)((p->offset) | 0);  /* check that 'array_1d.offset' is an integer */
  { datatype *tmp = &p->dtype; (void)tmp; }
  (void)((p->span) | 0);  /* check that 'array_1d.span' is an integer */
  { array_dims(*tmp)[1] = &p->dim; (void)tmp; }
}
struct _cffi_align__array_1d { char x; array_1d y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__array_2d(array_2d *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { void * *tmp = &p->base_addr; (void)tmp; }
  (void)((p->offset) | 0);  /* check that 'array_2d.offset' is an integer */
  { datatype *tmp = &p->dtype; (void)tmp; }
  (void)((p->span) | 0);  /* check that 'array_2d.span' is an integer */
  { array_dims(*tmp)[2] = &p->dim; (void)tmp; }
}
struct _cffi_align__array_2d { char x; array_2d y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__array_3d(array_3d *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { void * *tmp = &p->base_addr; (void)tmp; }
  (void)((p->offset) | 0);  /* check that 'array_3d.offset' is an integer */
  { datatype *tmp = &p->dtype; (void)tmp; }
  (void)((p->span) | 0);  /* check that 'array_3d.span' is an integer */
  { array_dims(*tmp)[3] = &p->dim; (void)tmp; }
}
struct _cffi_align__array_3d { char x; array_3d y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__array_4d(array_4d *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { void * *tmp = &p->base_addr; (void)tmp; }
  (void)((p->offset) | 0);  /* check that 'array_4d.offset' is an integer */
  { datatype *tmp = &p->dtype; (void)tmp; }
  (void)((p->span) | 0);  /* check that 'array_4d.span' is an integer */
  { array_dims(*tmp)[4] = &p->dim; (void)tmp; }
}
struct _cffi_align__array_4d { char x; array_4d y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__array_5d(array_5d *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { void * *tmp = &p->base_addr; (void)tmp; }
  (void)((p->offset) | 0);  /* check that 'array_5d.offset' is an integer */
  { datatype *tmp = &p->dtype; (void)tmp; }
  (void)((p->span) | 0);  /* check that 'array_5d.span' is an integer */
  { array_dims(*tmp)[5] = &p->dim; (void)tmp; }
}
struct _cffi_align__array_5d { char x; array_5d y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__array_6d(array_6d *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { void * *tmp = &p->base_addr; (void)tmp; }
  (void)((p->offset) | 0);  /* check that 'array_6d.offset' is an integer */
  { datatype *tmp = &p->dtype; (void)tmp; }
  (void)((p->span) | 0);  /* check that 'array_6d.span' is an integer */
  { array_dims(*tmp)[6] = &p->dim; (void)tmp; }
}
struct _cffi_align__array_6d { char x; array_6d y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__array_7d(array_7d *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { void * *tmp = &p->base_addr; (void)tmp; }
  (void)((p->offset) | 0);  /* check that 'array_7d.offset' is an integer */
  { datatype *tmp = &p->dtype; (void)tmp; }
  (void)((p->span) | 0);  /* check that 'array_7d.span' is an integer */
  { array_dims(*tmp)[7] = &p->dim; (void)tmp; }
}
struct _cffi_align__array_7d { char x; array_7d y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__array_dims(array_dims *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->stride) | 0);  /* check that 'array_dims.stride' is an integer */
  (void)((p->lower_bound) | 0);  /* check that 'array_dims.lower_bound' is an integer */
  (void)((p->extent) | 0);  /* check that 'array_dims.extent' is an integer */
}
struct _cffi_align__array_dims { char x; array_dims y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__datatype(datatype *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->len) | 0);  /* check that 'datatype.len' is an integer */
  (void)((p->ver) | 0);  /* check that 'datatype.ver' is an integer */
  (void)((p->rank) | 0);  /* check that 'datatype.rank' is an integer */
  (void)((p->type) | 0);  /* check that 'datatype.type' is an integer */
  (void)((p->attribute) | 0);  /* check that 'datatype.attribute' is an integer */
}
struct _cffi_align__datatype { char x; datatype y; };

static double *_cffi_var___new_vmec_stuff_mod_MOD_h_phi(void)
{
  return &(__new_vmec_stuff_mod_MOD_h_phi);
}

static double *_cffi_var___new_vmec_stuff_mod_MOD_h_theta(void)
{
  return &(__new_vmec_stuff_mod_MOD_h_theta);
}

static double *_cffi_var___new_vmec_stuff_mod_MOD_rmajor(void)
{
  return &(__new_vmec_stuff_mod_MOD_rmajor);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "__cut_detector_global_MOD_init", (void *)_cffi_f___cut_detector_global_MOD_init, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 0), (void *)_cffi_d___cut_detector_global_MOD_init },
  { "__cut_detector_global_MOD_trace_to_cut", (void *)_cffi_f___cut_detector_global_MOD_trace_to_cut, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 3), (void *)_cffi_d___cut_detector_global_MOD_trace_to_cut },
  { "__neo_orb_global_MOD_init_field", (void *)_cffi_f___neo_orb_global_MOD_init_field, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 21), (void *)_cffi_d___neo_orb_global_MOD_init_field },
  { "__neo_orb_global_MOD_init_integrator", (void *)_cffi_f___neo_orb_global_MOD_init_integrator, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 0), (void *)_cffi_d___neo_orb_global_MOD_init_integrator },
  { "__neo_orb_global_MOD_init_params", (void *)_cffi_f___neo_orb_global_MOD_init_params, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 13), (void *)_cffi_d___neo_orb_global_MOD_init_params },
  { "__neo_orb_global_MOD_timestep_sympl_z", (void *)_cffi_f___neo_orb_global_MOD_timestep_sympl_z, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 9), (void *)_cffi_d___neo_orb_global_MOD_timestep_sympl_z },
  { "__neo_orb_global_MOD_timestep_z", (void *)_cffi_f___neo_orb_global_MOD_timestep_z, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 9), (void *)_cffi_d___neo_orb_global_MOD_timestep_z },
  { "__new_vmec_stuff_mod_MOD_h_phi", (void *)_cffi_var___new_vmec_stuff_mod_MOD_h_phi, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 50), (void *)0 },
  { "__new_vmec_stuff_mod_MOD_h_theta", (void *)_cffi_var___new_vmec_stuff_mod_MOD_h_theta, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 50), (void *)0 },
  { "__new_vmec_stuff_mod_MOD_rmajor", (void *)_cffi_var___new_vmec_stuff_mod_MOD_rmajor, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 50), (void *)0 },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "base_addr", offsetof(array_1d, base_addr),
                 sizeof(((array_1d *)0)->base_addr),
                 _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "offset", offsetof(array_1d, offset),
              sizeof(((array_1d *)0)->offset),
              _CFFI_OP(_CFFI_OP_NOOP, 56) },
  { "dtype", offsetof(array_1d, dtype),
             sizeof(((array_1d *)0)->dtype),
             _CFFI_OP(_CFFI_OP_NOOP, 49) },
  { "span", offsetof(array_1d, span),
            sizeof(((array_1d *)0)->span),
            _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "dim", offsetof(array_1d, dim),
           sizeof(((array_1d *)0)->dim),
           _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "base_addr", offsetof(array_2d, base_addr),
                 sizeof(((array_2d *)0)->base_addr),
                 _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "offset", offsetof(array_2d, offset),
              sizeof(((array_2d *)0)->offset),
              _CFFI_OP(_CFFI_OP_NOOP, 56) },
  { "dtype", offsetof(array_2d, dtype),
             sizeof(((array_2d *)0)->dtype),
             _CFFI_OP(_CFFI_OP_NOOP, 49) },
  { "span", offsetof(array_2d, span),
            sizeof(((array_2d *)0)->span),
            _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "dim", offsetof(array_2d, dim),
           sizeof(((array_2d *)0)->dim),
           _CFFI_OP(_CFFI_OP_NOOP, 37) },
  { "base_addr", offsetof(array_3d, base_addr),
                 sizeof(((array_3d *)0)->base_addr),
                 _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "offset", offsetof(array_3d, offset),
              sizeof(((array_3d *)0)->offset),
              _CFFI_OP(_CFFI_OP_NOOP, 56) },
  { "dtype", offsetof(array_3d, dtype),
             sizeof(((array_3d *)0)->dtype),
             _CFFI_OP(_CFFI_OP_NOOP, 49) },
  { "span", offsetof(array_3d, span),
            sizeof(((array_3d *)0)->span),
            _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "dim", offsetof(array_3d, dim),
           sizeof(((array_3d *)0)->dim),
           _CFFI_OP(_CFFI_OP_NOOP, 39) },
  { "base_addr", offsetof(array_4d, base_addr),
                 sizeof(((array_4d *)0)->base_addr),
                 _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "offset", offsetof(array_4d, offset),
              sizeof(((array_4d *)0)->offset),
              _CFFI_OP(_CFFI_OP_NOOP, 56) },
  { "dtype", offsetof(array_4d, dtype),
             sizeof(((array_4d *)0)->dtype),
             _CFFI_OP(_CFFI_OP_NOOP, 49) },
  { "span", offsetof(array_4d, span),
            sizeof(((array_4d *)0)->span),
            _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "dim", offsetof(array_4d, dim),
           sizeof(((array_4d *)0)->dim),
           _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "base_addr", offsetof(array_5d, base_addr),
                 sizeof(((array_5d *)0)->base_addr),
                 _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "offset", offsetof(array_5d, offset),
              sizeof(((array_5d *)0)->offset),
              _CFFI_OP(_CFFI_OP_NOOP, 56) },
  { "dtype", offsetof(array_5d, dtype),
             sizeof(((array_5d *)0)->dtype),
             _CFFI_OP(_CFFI_OP_NOOP, 49) },
  { "span", offsetof(array_5d, span),
            sizeof(((array_5d *)0)->span),
            _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "dim", offsetof(array_5d, dim),
           sizeof(((array_5d *)0)->dim),
           _CFFI_OP(_CFFI_OP_NOOP, 43) },
  { "base_addr", offsetof(array_6d, base_addr),
                 sizeof(((array_6d *)0)->base_addr),
                 _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "offset", offsetof(array_6d, offset),
              sizeof(((array_6d *)0)->offset),
              _CFFI_OP(_CFFI_OP_NOOP, 56) },
  { "dtype", offsetof(array_6d, dtype),
             sizeof(((array_6d *)0)->dtype),
             _CFFI_OP(_CFFI_OP_NOOP, 49) },
  { "span", offsetof(array_6d, span),
            sizeof(((array_6d *)0)->span),
            _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "dim", offsetof(array_6d, dim),
           sizeof(((array_6d *)0)->dim),
           _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "base_addr", offsetof(array_7d, base_addr),
                 sizeof(((array_7d *)0)->base_addr),
                 _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "offset", offsetof(array_7d, offset),
              sizeof(((array_7d *)0)->offset),
              _CFFI_OP(_CFFI_OP_NOOP, 56) },
  { "dtype", offsetof(array_7d, dtype),
             sizeof(((array_7d *)0)->dtype),
             _CFFI_OP(_CFFI_OP_NOOP, 49) },
  { "span", offsetof(array_7d, span),
            sizeof(((array_7d *)0)->span),
            _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "dim", offsetof(array_7d, dim),
           sizeof(((array_7d *)0)->dim),
           _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "stride", offsetof(array_dims, stride),
              sizeof(((array_dims *)0)->stride),
              _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "lower_bound", offsetof(array_dims, lower_bound),
                   sizeof(((array_dims *)0)->lower_bound),
                   _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "extent", offsetof(array_dims, extent),
              sizeof(((array_dims *)0)->extent),
              _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "len", offsetof(datatype, len),
           sizeof(((datatype *)0)->len),
           _CFFI_OP(_CFFI_OP_NOOP, 56) },
  { "ver", offsetof(datatype, ver),
           sizeof(((datatype *)0)->ver),
           _CFFI_OP(_CFFI_OP_NOOP, 52) },
  { "rank", offsetof(datatype, rank),
            sizeof(((datatype *)0)->rank),
            _CFFI_OP(_CFFI_OP_NOOP, 55) },
  { "type", offsetof(datatype, type),
            sizeof(((datatype *)0)->type),
            _CFFI_OP(_CFFI_OP_NOOP, 55) },
  { "attribute", offsetof(datatype, attribute),
                 sizeof(((datatype *)0)->attribute),
                 _CFFI_OP(_CFFI_OP_NOOP, 54) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "array_1d", 27, _CFFI_F_CHECK_FIELDS,
    sizeof(array_1d), offsetof(struct _cffi_align__array_1d, y), 0, 5 },
  { "array_2d", 28, _CFFI_F_CHECK_FIELDS,
    sizeof(array_2d), offsetof(struct _cffi_align__array_2d, y), 5, 5 },
  { "array_3d", 29, _CFFI_F_CHECK_FIELDS,
    sizeof(array_3d), offsetof(struct _cffi_align__array_3d, y), 10, 5 },
  { "array_4d", 30, _CFFI_F_CHECK_FIELDS,
    sizeof(array_4d), offsetof(struct _cffi_align__array_4d, y), 15, 5 },
  { "array_5d", 31, _CFFI_F_CHECK_FIELDS,
    sizeof(array_5d), offsetof(struct _cffi_align__array_5d, y), 20, 5 },
  { "array_6d", 32, _CFFI_F_CHECK_FIELDS,
    sizeof(array_6d), offsetof(struct _cffi_align__array_6d, y), 25, 5 },
  { "array_7d", 33, _CFFI_F_CHECK_FIELDS,
    sizeof(array_7d), offsetof(struct _cffi_align__array_7d, y), 30, 5 },
  { "array_dims", 34, _CFFI_F_CHECK_FIELDS,
    sizeof(array_dims), offsetof(struct _cffi_align__array_dims, y), 35, 3 },
  { "datatype", 49, _CFFI_F_CHECK_FIELDS,
    sizeof(datatype), offsetof(struct _cffi_align__datatype, y), 38, 5 },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "array_1d", 27 },
  { "array_2d", 28 },
  { "array_3d", 29 },
  { "array_4d", 30 },
  { "array_5d", 31 },
  { "array_6d", 32 },
  { "array_7d", 33 },
  { "array_dims", 34 },
  { "datatype", 49 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  NULL,  /* no enums */
  _cffi_typenames,
  10,  /* num_globals */
  9,  /* num_struct_unions */
  0,  /* num_enums */
  9,  /* num_typenames */
  NULL,  /* no includes */
  59,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit__simple(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit__simple(void) { return NULL; }
#  else
     init_simple(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit__simple(void)
{
  return _cffi_init("_simple", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
init_simple(void)
{
  _cffi_init("_simple", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
